### ISSUE TITLE
Crashes after putting in infor 

### ISSUE THREAD

**Issue by acooper1948** [SlayterDev/passwd-bugs#1]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device Info (please complete the following information):**
 - OS: [e.g. iOS 13]
 - Device [e.g. iPhone 12 Pro]
 - App Version [e.g. 1.0 (8)]

**Additional context**

**Comment by SlayterDev** [comment]
Closing for lack of information
